version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/employee
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
networks: 
  mynetwork: 
    driver: bridge